In [1]:
# setup stuff
import pandas as pd

In [2]:
# flights profiling

# this loads the jsonl file into a data frame
df_flights = pd.read_json("../data/raw/google_flights.jsonl", lines=True)

# this describes or 'profiles' df_flights 
print("Shape:", df_flights.shape)
print("\n--- Info ---")
df_flights.info()

# prints the first three rows
print("\n--- Head ---")
print(df_flights.head(3))

# iirc this counts the number of missing values, perhaps by column?
# lotsa missing target_date due to rolling collection not having a target date (this is expected)
print("\n--- Missing Values ---")
print(df_flights.isnull().sum())

Shape: (304, 12)

--- Info ---
<class 'pandas.DataFrame'>
RangeIndex: 304 entries, 0 to 303
Data columns (total 12 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   dateTime_collected  304 non-null    str
 1   status              304 non-null    str
 2   primary_source      304 non-null    bool
 3   collection_mode     304 non-null    str
 4   flights             304 non-null    object
 5   total_duration      304 non-null    int64
 6   carbon_emissions    304 non-null    object
 7   price               304 non-null    int64
 8   type                304 non-null    str
 9   airline_logo        304 non-null    str
 10  booking_token       304 non-null    str
 11  target_date         169 non-null    str
dtypes: bool(1), int64(2), object(2), str(7)
memory usage: 26.6+ KB

--- Head ---
  dateTime_collected   status  primary_source collection_mode  \
0         2026-09-02  success            True         rolling
1         2026-09-02  success            True         rolling
2         2026-09-02  success            True         rolling

                                             flights  total_duration  \
0  [{'departure_airport': {'name': 'Ninoy Aquino ...              85
1  [{'departure_airport': {'name': 'Ninoy Aquino ...              85
2  [{'departure_airport': {'name': 'Ninoy Aquino ...              75

                                    carbon_emissions  price     type  \
0  {'this_flight': 47000, 'typical_for_this_route...   2900  One way
1  {'this_flight': 47000, 'typical_for_this_route...   3236  One way
2  {'this_flight': 62000, 'typical_for_this_route...   3292  One way

                                        airline_logo  \
0  https://www.gstatic.com/flights/airline_logos/...
1  https://www.gstatic.com/flights/airline_logos/...
2  https://www.gstatic.com/flights/airline_logos/...

                                       booking_token target_date
0  WyJDalJJUlVsb1JuRnhUa3hCT0dkQlJXZzBMV2RDUnkwdE...         NaN
1  WyJDalJJUlVsb1JuRnhUa3hCT0dkQlJXZzBMV2RDUnkwdE...         NaN
2  WyJDalJJUlVsb1JuRnhUa3hCT0dkQlJXZzBMV2RDUnkwdE...         NaN

--- Missing Values ---
dateTime_collected      0
status                  0
primary_source          0
collection_mode         0
flights                 0
total_duration          0
carbon_emissions        0
price                   0
type                    0
airline_logo            0
booking_token           0
target_date           135
dtype: int64

In [3]:
# trends profiling

# this loads the jsonl file into a data frame
df_trends = pd.read_json("../data/raw/google_trends.jsonl", lines=True)

# this describes or 'profiles' df_trends 
print("Shape:", df_trends.shape)
print("\n--- Info ---")
df_trends.info()

# prints the first three rows
print("\n--- Head ---")
print(df_trends.head(3))

# iirc this counts the number of missing values, perhaps by column?
print("\n--- Missing Values ---")
print(df_trends.isnull().sum())

Shape: (1209, 6)

--- Info ---
<class 'pandas.DataFrame'>
RangeIndex: 1209 entries, 0 to 1208
Data columns (total 6 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   dateTime_collected  1209 non-null   str
 1   status              1209 non-null   str
 2   primary_source      1209 non-null   bool
 3   collection_mode     1209 non-null   str
 4   timestamp           1209 non-null   datetime64[s]
 5   value               1209 non-null   int64
dtypes: bool(1), datetime64[s](1), int64(1), str(3)
memory usage: 48.5 KB

--- Head ---
  dateTime_collected   status  primary_source collection_mode  timestamp  \
0         2026-09-02  success            True         rolling 2026-06-02
1         2026-09-02  success            True         rolling 2026-06-03
2         2026-09-02  success            True         rolling 2026-06-04

   value
0     51
1      0
2      0

--- Missing Values ---
dateTime_collected    0
status                0
primary_source        0
collection_mode       0
timestamp             0
value                 0
dtype: int64

In [4]:
# hotels profiling

# this loads the jsonl file into a data frame
df_hotels = pd.read_json("../data/raw/google_hotels.jsonl", lines=True)

# this describes or 'profiles' df_hotels 
print("Shape:", df_hotels.shape)
print("\n--- Info ---")
df_hotels.info()

# prints the first three rows
print("\n--- Head ---")
print(df_hotels.head(3))

# iirc this counts the number of missing values, perhaps by column?
print("\n--- Missing Values ---")
print(df_hotels.isnull().sum())

Shape: (518, 9)

--- Info ---
<class 'pandas.DataFrame'>
RangeIndex: 518 entries, 0 to 517
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   dateTime_collected  518 non-null    str
 1   status              518 non-null    str
 2   primary_source      518 non-null    bool
 3   collection_mode     518 non-null    str
 4   hotel_name          518 non-null    str
 5   lowest_Rate         518 non-null    str
 6   check_in            518 non-null    str
 7   check_out           518 non-null    str
 8   target_date         258 non-null    str
dtypes: bool(1), str(8)
memory usage: 33.0 KB

--- Head ---
  dateTime_collected   status  primary_source collection_mode  \
0         2026-09-02  success            True         rolling
1         2026-09-02  success            True         rolling
2         2026-09-02  success            True         rolling

                                          hotel_name lowest_Rate    check_in  \
0                                  North Tourist Inn      ₱1,211  2026-09-03
1                                AVENUE SUITES HOTEL      ₱1,913  2026-09-03
2  UrbanView @ Lacson Street Bacolod City by RedD...      ₱1,249  2026-09-03

    check_out target_date
0  2026-09-04         NaN
1  2026-09-04         NaN
2  2026-09-04         NaN

--- Missing Values ---
dateTime_collected      0
status                  0
primary_source          0
collection_mode         0
hotel_name              0
lowest_Rate             0
check_in                0
check_out               0
target_date           260
dtype: int64

In [5]:
# quick statistical summary of the flights data using .describe
# TODO: might need to further clean data that are objects/string php amount
print("flights summary:")
display(df_flights.describe())

# number of entries per specified categories
print("flights rate value counts / distribution")
print(df_flights["collection_mode"].value_counts())
print(df_flights["status"].value_counts())

flights summary:

       total_duration        price
count      304.000000   304.000000
mean        80.493421  3192.805921
std          5.194560  1247.325585
min         70.000000  1913.000000
25%         75.000000  2396.000000
50%         85.000000  2731.000000
75%         85.000000  3684.000000
max         85.000000  9900.000000

flights rate value counts / distribution
collection_mode
festival_target    169
rolling            135
Name: count, dtype: int64
status
success    304
Name: count, dtype: int64

In [6]:
# quick statistical summary of the hotels data using .describe
# TODO: might need to further clean data that are objects/string php amount
print("hotels summary:")
display(df_hotels.describe())

# number of entries per specified categories
print("hotels rate value counts / distribution")
print(df_hotels["collection_mode"].value_counts())
print(df_hotels["status"].value_counts())

hotels summary:

,dateTime_collected,status,primary_source,collection_mode,hotel_name,lowest_Rate,check_in,check_out,target_date
count,518,518,518,518,518,518,518,518,258
unique,12,1,1,2,65,346,13,13,1
top,2026-09-04,success,True,rolling,Park Inn by Radisson Bacolod,"₱2,464",2026-10-09,2026-10-13,2026-10-09
freq,78,518,518,260,26,11,258,258,258

hotels rate value counts / distribution
collection_mode
rolling            260
festival_target    258
Name: count, dtype: int64
status
success    518
Name: count, dtype: int64

In [7]:
# quick statistical summary of the trends data using .describe
# TODO: might need to further clean data that are objects/string php amount
print("trends summary:")
display(df_trends.describe())

# number of entries per specified categories
print("trends rate value counts / distribution")
print(df_trends["collection_mode"].value_counts())
print(df_trends["status"].value_counts())

trends summary:

                 timestamp        value
count                 1209  1209.000000
mean   2026-07-23 05:32:18    26.384615
min    2026-06-02 00:00:00     0.000000
25%    2026-06-30 00:00:00     0.000000
50%    2026-07-23 00:00:00     0.000000
75%    2026-08-15 00:00:00    51.000000
max    2026-09-13 00:00:00   100.000000
std                    NaN    28.976386

trends rate value counts / distribution
collection_mode
rolling    1209
Name: count, dtype: int64
status
success    1209
Name: count, dtype: int64

In [9]:
festival_flights = df_flights[df_flights["collection_mode"] == "festival_target"]
print("Festival Target Flights ", len(festival_flights))

flight_subset = df_flights[["dateTime_collected","collection_mode", "price", "total_duration"]]
print(flight_subset.head())

Festival Target Flights  169
  dateTime_collected collection_mode  price  total_duration
0         2026-09-02         rolling   2900              85
1         2026-09-02         rolling   3236              85
2         2026-09-02         rolling   3292              75
3         2026-09-02         rolling   3684              80
4         2026-09-02         rolling   3684              85